name: TERRAFORM PROJ

on:
  push:
   branches: [ master ]
   # tags:
     # - v1.**

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn package
    
