name: TERRAFORM PROJ

on:
  push:
   branches: [ master ]
   # tags:
   # - v1.**

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven project
      run: mvn package
    
